"""Add location to users

Revision ID: 0d3ce80e0ffb
Revises: d02aad505b33
Create Date: 2025-11-02 15:42:38.953231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3ce80e0ffb'
down_revision: Union[str, Sequence[str], None] = 'd02aad505b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Add is_active with a temporary server default to backfill existing rows,
    then drop the default to match the ORM semantics.
    """
    # Add with default TRUE so existing rows get a value
    op.add_column(
        'users',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    # Remove server default (keep NOT NULL)
    op.alter_column('users', 'is_active', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
