"""Add location to users

Revision ID: a121c1332451
Revises: b8dc38d6a07e
Create Date: 2025-11-01 18:38:30.000828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a121c1332451'
down_revision: Union[str, Sequence[str], None] = 'b8dc38d6a07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('device_location', sa.String(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('project_manager', 'supervisor', 'driver', 'delivery_associate', 'sweeper', name='roleenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('project_manager', 'supervisor', 'driver', 'delivery_associate', 'sweeper', name='roleenum'),
               nullable=True)
    op.drop_column('user_sessions', 'device_location')
    # ### end Alembic commands ###
